### PR TITLE
7.10.3: Fix #388, #380, #349

### LINKED ISSUE #388: HTML sanitizer bypass
**Describe the bug**
HTML sanitizer in RoosterJS can be bypassed.

**To Reproduce**
1. Go to https://microsoft.github.io/roosterjs/index.html
2. Click on show side pane
3. Click on API Playground
4. Select HTML sanitizer
5. Add following to the input
```
<a href="javascript
:alert(1)">test</a>
```
6. Click on Sanitize button
7. JavaScript URL is still there

**Expected behavior**
Empty anchor tag

**Device Information**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

### PR DESCRIPTION
**Pull request by JiuqingSong**
#349 ToggleHeader doesn't remove current font-size
Currently we only remove 'font-size' for selected inlineElement. But we actually should do this for all related BlockElements, and use HtmlSanitizer to help loop each elements

#380 Hyperlinks absorb all text/images pasted next to them
We already have a similar fix for inserting text for Firefox, we just need to also apply that fix to paste event in all browsers

#388 HTML sanitizer bypass
Add a XSS check to the link url when insert link using HtmlSanitizer

Bump version to 7.10.3

### CODE REVIEW

File: packages/roosterjs-editor-api/lib/format/createLink.ts [hunk 1]
```diff
@@ -54,7 +55,7 @@ export default function createLink(
     displayText?: string
 ) {
     editor.focus();
-    let url = link ? link.trim() : '';
+    let url = (checkXss(link) || '').trim();
```
Comment (titrongt) [inline packages/roosterjs-editor-api/lib/format/createLink.ts]: Add back the check to make sure link is defined? `checkXss `should work anyways, but would prevent a bit of unnecessary work

File: packages/roosterjs-editor-core/lib/corePlugins/FirefoxTypeAfterLink.ts [hunk 2]
```diff
@@ -1,13 +1,15 @@
...
 import { PluginEvent, PluginEventType, PositionType } from 'roosterjs-editor-types';
 
 /**
  * FirefoxTypeAfterLink Component helps handle typing event when cursor is right after a link.
- * When typing after a link, Firefox will always put the new charactor inside link.
- * This plugin overrides this behavior to make it consistent with other browsers.
+ * When typing/pasting after a link, browser may put the new charactor inside link.
+ * This plugin overrides this behavior to always insert outside of link.
+ *
+ * TODO: Rename this file in next major release since it is not only applied to Firefox now
```
Comment (titrongt) [inline packages/roosterjs-editor-core/lib/corePlugins/FirefoxTypeAfterLink.ts]: Is this comment up to date? I see there is a check that makes sure this is Firefox

Comment (JiuqingSong) [reply packages/roosterjs-editor-core/lib/corePlugins/FirefoxTypeAfterLink.ts]: The keyPress event needs isFirefox check. PasteEvent should apply to all browsers

File: packages/roosterjs-editor-api/lib/format/createLink.ts (hunk 1 above)
Comment (JiuqingSong) [reply packages/roosterjs-editor-api/lib/format/createLink.ts]: I think they both work, no difference.

**Comment by titrongt** [comment]
A few minor comments but overall looks good to me 👍🏼
