### PR TITLE
Fix #1322: Copying some table structure transform the table to single line text

### LINKED ISSUE #1322: Copying tables turns them into single line
**Describe the bug**

Copying and pasting in a certain way causes the table to turn into a single line.

**To Reproduce**
1. Copy this table into the roosterjs demo site: 
<table><tr><td>1</td><td>2</td><td>3</td></tr><tr><td>4</td><td>5</td><td>6</td></tr><tr><td>7</td><td>8</td><td>9</td></tr></table>

2. Paste the table on the editor

3. Copy the table on the editor while using table selection, the table needs to look all greyed out

4. Paste it again, it will turn into a line

**Expected behavior**
Table pastes like normal. This behaviour can be seen if the table is copied using normal selection, where the contents of the table are highlighted blue.

**Device Information**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 8.33.1

### PR DESCRIPTION
**Pull request by BryanValverdeU**
The problem: #1322

Copying some tables are not adding the table tag, this seems to be a Browser issue. 

image

To fix this add an additional element to the temp div to prevent the table tags to not be added to the clipboard

### CODE REVIEW

File: packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts [hunk 1]
```diff
@@ -228,7 +228,16 @@ function selectionExToRange(
     let newRange: Range | null = null;
     if (selection.type === SelectionRangeTypes.TableSelection && selection.coordinates) {
         const table = tempDiv.querySelector(`#${selection.table.id}`) as HTMLTableElement;
-        newRange = createRange(table);
+        const elementAfter = table.parentElement?.insertBefore(
```
Comment (JiuqingSong) [inline packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts:231]: I think this should be done when we write content model back to DOM, no matter if it is table selection. For example, when handleTable (may need a wrapper handler for table for cut/copy), we directly write a SPAN around TABLE element

Comment (JiuqingSong) [reply packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts:231]: Then we convert the table selection directly to a regular selection, then here it can select the whole SPAN. (or maybe a DIV will be better)

Comment (BryanValverdeU) [reply packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts]: Sounds good.
Updated the PR to change the handleTable behavior to add a div around the table.

File: packages/roosterjs-content-model/lib/modelToDom/handlers/handleTable.ts [hunk 2]
```diff
@@ -29,10 +29,12 @@ export const handleTable: ContentModelBlockHandler<ContentModelTable> = (
 
         moveChildNodes(tableNode);
     } else {
+        const tableContainer = doc.createElement('div');
```
Comment (JiuqingSong) [inline packages/roosterjs-content-model/lib/modelToDom/handlers/handleTable.ts:32]: Add comment to explain why we need this DIV.

Question: Do we want to apply this DIV to all tables, or only when cut/copy?

Comment (BryanValverdeU) [reply packages/roosterjs-content-model/lib/modelToDom/handlers/handleTable.ts:32]: We can keep it only for cut and paste.

File: packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts [hunk 3]
```diff
@@ -119,6 +123,11 @@ export default class ContentModelCopyPastePlugin implements PluginWithState<Copy
                 {
                     isDarkMode: false /* To force light mode on paste */,
                     darkColorHandler: this.editor.getDarkColorHandler(),
+                },
+                {
+                    modelHandlerOverride: {
+                        table: copyCutTableHandler,
```
Comment (JiuqingSong) [inline packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts:129]: You can leverage the onNodeCreated parameter from ModelToDomOption. It will be called when a node is created, then you can check if it is a table then wrap it.

Using a customized handler here is fine, but using cachedElement is not a good idea here.

Comment (JiuqingSong) [reply packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts:129]: There is an exmaple about how to use this parameter in packages\roosterjs-content-model\lib\publicApi\link\insertLink.ts

**Review by JiuqingSong — APPROVED** [review]
